default_stages: [commit]
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v2.0.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
  - repo: https://github.com/python-poetry/poetry
    rev: "1.2.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--check]
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: poetry run autoflake -r -i --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy .
        require_serial: true
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
