tagFormat: "${version}"
branches:
  - "master"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - publishCmd: |
        export CI_COMMIT_TAG="true"
        poetry version "${nextRelease.version}"
        poetry run mkdocs gh-deploy --force
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - pyproject.toml
  - "@semantic-release/github"
