site_name: Revelio
repo_url: https://github.com/ndido98/revelio

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

watch:
  - src/revelio

nav:
  - Introduction: index.md
  - Configuration file reference: config-reference/
  - Reference: reference/
  - changelog.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - abbr
  - attr_list

plugins:
  - search:
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_signature_annotations: true
            show_source: true
