name: Setup Python and Poetry environment

inputs:
  python-version:
    required: false
    description: 'Python version'
    default: '3.10'
outputs: {}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      shell: bash
      run: python -m pip install poetry
    - name: Create virtual environment
      shell: bash
      run: poetry install
