name: Test and release

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download actionlint
        shell: bash
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        shell: bash
        run: ./actionlint -color

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python and Poetry environment
        uses: ./.github/actions/python-poetry-env
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python and Poetry environment
        uses: ./.github/actions/python-poetry-env
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: poetry run pytest

  release:
    runs-on: ubuntu-latest
    needs: [actionlint, pre-commit, test]
    if: github.event_name != 'pull_request' && github.repository == 'ndido98/revelio' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Setup Python and Poetry environment
        uses: ./.github/actions/python-poetry-env
      - name: Run semantic-release
        shell: bash
        run: |
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
